export const hostName = 'http://localhost:3000'
export const hostNameTradar = 'http://tradar-thinklabs.mybluemix.net'
export const api_v1 = {
  //uptocase
  'AUTHEN_LOGIN': '/api/v1/user',
  'USER': '/api/v1/user',
  'ADMIN_UNIT': '/api/v1/units',
  'ADMIN_UNIT_MANAGER': '/api/v1/user/unit-manager',
  'GET_PROFILE': '/api/v1/user/infor',
  'AVATAR': '/api/v1/user/avatar',
  'BTS': '/api/v1/bts',
  'LIST_BTS_BY_LIST_UNIT': '/api/v1/units/bts?',
  'CREATE_INSPECTION': '/api/v1/ins',
  'INSPECTION': '/api/v1/ins',
  'INSPECTION_RECORD': '/api/v1/ins-record',
  'INSPECTION_RECORD_CATEGORY_SELECTED': '/api/v1/ins-record/category-selected',
  'STATUS_INSPECTION': '/api/v1/ins-status',
  'RATING': '/api/v1/rating',
  'IMAGE': '/api/v1/image',
  'CATEGORY': '/api/v1/categoris',
  'CHECK_LIST': '/api/v1/checklist',
  'ROLE': '/api/v1/role',
  'INSP_STATUS': '/api/v1/ins-status',
  'ITEM': '/api/v1/items',
  'MY_BTS': '/api/v1/bts/my',
  'VIEW_IMAGE': '/api/v1/image/preview',
  'DRONE': '/api/v1/drones',
  'DRONE_MANAGEMENT': '/api/v1/drone-management',
  'POSITION_RECORD': '/api/v1/p-record',
  'POSITION_RATING': '/api/v1/position-rating',
  'APLICATION': '/api/v1/application',
  'BTS_TYPE': '/api/v1/bts-type',
  'CATEGORY_RECORD': '/api/v1/category-record',
  'DRONE_USE_HISTORY': '/api/v1/drone-use',
  'REPORT': '/api/v1/report',
  'ITEM_MAPING': '/api/v1/pos-item-map',
  'POSITION_MAPING': '/api/v1/pos-item-map/position',
  'EVAL_CRITERIA': '/api/v1/eval-criteria',
  'INSP_RECORD_RATING': '/api/v1/insp-record-rating',
  'BTS_ATTRIBUTE': '/api/v1/bts-attribute',
  'LOGGING_SYSTEM': '/api/v1/sys-logging'
};