export const province = [
  {id: '01',  name:'Hà Nội'},
  {id: '38',  name:	'Thanh Hoá'}
  /*{id: '02',  name:	'Hà Giang'},
  {id: '04',  name:	'Cao Bằng'},
  {id: '06',  name:	'Bắc Kạn'},
  {id: '08',  name:	'Tuyên Quang'},
  {id: '10',  name:	'Lào Cai'},
  {id: '11',  name:	'Điện Biên'},
  {id: '12',  name:	'Lai Châu'},
  {id: '14',  name:	'Sơn La'},
  {id: '15',  name:	'Yên Bái'},
  {id: '17',  name:	'Hoà Bình'},
  {id: '19',  name:	'Thái Nguyên'},
  {id: '20',  name:	'Lạng Sơn'},
  {id: '22',  name:	'Quảng Ninh'},
  {id: '24',  name:	'Bắc Giang'},
  {id: '25',  name:	'Phú Thọ'},
  {id: '26',  name:	'Vĩnh Phúc'},
  {id: '27',  name:	'Bắc Ninh'},
  {id: '30',  name:	'Hải Dương'},
  {id: '31',  name:	'Hải Phòng'},
  {id: '33',  name:	'Hưng Yên'},
  {id: '34',  name:	'Thái Bình'},
  {id: '35',  name:	'Hà Nam'},
  {id: '36',  name:	'Nam Định'},
  {id: '37',  name:	'Ninh Bình'},
  {id: '40',  name:	'Nghệ An'},
  {id: '42',  name:	'Hà Tĩnh'},
  {id: '44',  name:	'Quảng Bình'},
  {id: '45',  name:	'Quảng Trị'},
  {id: '46',  name:	'Thừa Thiên Huế'},
  {id: '48',  name:	'Đà Nẵng'},
  {id: '49',  name:	'Quảng Nam'},
  {id: '51',  name:	'Quảng Ngãi'},
  {id: '52',  name:	'Bình Định'},
  {id: '54',  name:	'Phú Yên'},
  {id: '56',  name:	'Khánh Hoà'},
  {id: '58',  name:	'Ninh Thuận'},
  {id: '60',  name:	'Bình Thuận'},
  {id: '62',  name:	'Kon Tum'},
  {id: '64',  name:	'Gia Lai'},
  {id: '66',  name:	'Đắk Lắk'},
  {id: '67',  name:	'Đắk Nông'},
  {id: '68',  name:	'Lâm Đồng'},
  {id: '70',  name:	'Bình Phước'},
  {id: '72',  name:	'Tây Ninh'},
  {id: '74',  name:	'Bình Dương'},
  {id: '75',  name:	'Đồng Nai'},
  {id: '77',  name:	'Bà Rịa - Vũng Tàu'},
  {id: '79',  name:	'Hồ Chí Minh'},
  {id: '80',  name:	'Long An'},
  {id: '82',  name:	'Tiền Giang'},
  {id: '83',  name:	'Bến Tre'},
  {id: '84',  name:	'Trà Vinh'},
  {id: '86',  name:	'Vĩnh Long'},
  {id: '87',  name:	'Đồng Tháp'},
  {id: '89',  name:	'An Giang'},
  {id: '91',  name:	'Kiên Giang'},
  {id: '92',  name:	'Cần Thơ'},
  {id: '93',  name:	'Hậu Giang'},
  {id: '94',  name:	'Sóc Trăng'},
  {id: '95',  name:	'Bạc Liêu'},
  {id: '96',  name:	'Cà Mau'}*/
]
export const district = {
  '38': [
    { 'id': '3801', 'name': 'TP. Thanh Hóa'},
    { 'id': '3802', 'name': 'TP. Sầm Sơn'},
    { 'id': '3803', 'name': 'TX. Bỉm Sơn'},
    { 'id': '3804', 'name': 'Mường Lát'},
    { 'id': '3805', 'name': 'Quan Hóa'},
    { 'id': '3806', 'name': 'Bá Thước'},
    { 'id': '3807', 'name': 'Quan Sơn'},
    { 'id': '3808', 'name': 'Lang Chánh'},
    { 'id': '3809', 'name': 'Ngọc Lặc'},
    { 'id': '3810', 'name': 'Cẩm Thủy'},
    { 'id': '3811', 'name': 'Thạch Thành'},
    { 'id': '3812', 'name': 'Hà Trung'},
    { 'id': '3813', 'name': 'Vĩnh Lộc'},
    { 'id': '3814', 'name': 'Yên Định'},
    { 'id': '3815', 'name': 'Thọ Xuân'},
    { 'id': '3816', 'name': 'Thường Xuân'},
    { 'id': '3817', 'name': 'Triệu Sơn'},
    { 'id': '3818', 'name': 'Thiệu Hóa'},
    { 'id': '3819', 'name': 'Hoằng Hóa'},
    { 'id': '3820', 'name': 'Hậu Lộc'},
    { 'id': '3821', 'name': 'Nga Sơn'},
    { 'id': '3822', 'name': 'Như Xuân'},
    { 'id': '3823', 'name': 'Như Thanh'},
    { 'id': '3824', 'name': 'Nông Cống'},
    { 'id': '3825', 'name': 'Đông Sơn'},
    { 'id': '3826', 'name': 'Quảng Xương'},
    { 'id': '3827', 'name': 'Tĩnh Gia'}
  ],
  '01': [
    { 'id': '0101', 'name': 'Ba Đình'},
    { 'id': '0102', 'name': 'Hoàn Kiếm'},
    { 'id': '0103', 'name': 'Tây Hồ'},
    { 'id': '0104', 'name': 'Long Biên'},
    { 'id': '0105', 'name': 'Cầu Giấy'},
    { 'id': '0106', 'name': 'Đống Đa'},
    { 'id': '0107', 'name': 'Hai Bà Trưng'},
    { 'id': '0108', 'name': 'Hoàng Mai'},
    { 'id': '0109', 'name': 'Thanh Xuân'},
    { 'id': '0110', 'name': 'Hà Đông'},
    { 'id': '0111', 'name': 'Sơn Tây'},
    { 'id': '0112', 'name': 'Sóc Sơn'},
    { 'id': '0113', 'name': 'Đông Anh'},
    { 'id': '0114', 'name': 'Gia Lâm'},
    { 'id': '0115', 'name': 'Từ Liêm'},
    { 'id': '0116', 'name': 'Thanh Trì'},
    { 'id': '0117', 'name': 'Mê Linh'},
    { 'id': '0118', 'name': 'Ba Vì'},
    { 'id': '0119', 'name': 'Phúc Thọ'},
    { 'id': '0120', 'name': 'Đan Phượng'},
    { 'id': '0121', 'name': 'Hoài Đức'},
    { 'id': '0122', 'name': 'Quốc Oai'},
    { 'id': '0123', 'name': 'Thạch Thất'},
    { 'id': '0124', 'name': 'Chương Mỹ'},
    { 'id': '0125', 'name': 'Thanh Oai'},
    { 'id': '0126', 'name': 'Thường Tín'},
    { 'id': '0127', 'name': 'Phú Xuyên'},
    { 'id': '0128', 'name': 'Ứng Hòa'},
    { 'id': '0129', 'name': 'Mỹ Đức'}
  ]
}